import 'package:flutter/foundation.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/cart_item.dart';
import '../models/food_item.dart';
import '../models/order.dart';
import '../models/order_item.dart';
import '../services/order_service.dart';
import '../services/notification_service.dart';

class CartService extends ChangeNotifier {
  final List<CartItem> _items = [];
  final OrderService _orderService = OrderService();

  List<CartItem> get items => List.unmodifiable(_items);

  int get itemCount {
    return _items.fold(0, (total, item) => total + item.quantity);
  }

  double get subtotal {
    return _items.fold(0.0, (total, item) => total + item.totalPrice);
  }

  void addItem(FoodItem foodItem) {
    // Check if item already exists in cart
    final existingIndex = _items.indexWhere((item) => item.foodItem.id == foodItem.id);

    if (existingIndex >= 0) {
      // Item exists, increment quantity
      _items[existingIndex].increment();
    } else {
      // Add new item to cart
      _items.add(CartItem(foodItem: foodItem));
    }

    notifyListeners();
  }

  void removeItem(String foodItemId) {
    _items.removeWhere((item) => item.foodItem.id == foodItemId);
    notifyListeners();
  }

  void updateQuantity(String foodItemId, int quantity) {
    final index = _items.indexWhere((item) => item.foodItem.id == foodItemId);
    if (index >= 0) {
      if (quantity <= 0) {
        removeItem(foodItemId);
      } else {
        _items[index].quantity = quantity;
        notifyListeners();
      }
    }
  }

  void incrementItem(String foodItemId) {
    final index = _items.indexWhere((item) => item.foodItem.id == foodItemId);
    if (index >= 0) {
      _items[index].increment();
      notifyListeners();
    }
  }

  void decrementItem(String foodItemId) {
    final index = _items.indexWhere((item) => item.foodItem.id == foodItemId);
    if (index >= 0) {
      _items[index].decrement();
      if (_items[index].quantity == 0) {
        removeItem(foodItemId);
      }
      notifyListeners();
    }
  }

  void clearCart() {
    _items.clear();
    notifyListeners();
  }

  bool isInCart(String foodItemId) {
    return _items.any((item) => item.foodItem.id == foodItemId);
  }

  int getQuantity(String foodItemId) {
    final index = _items.indexWhere((item) => item.foodItem.id == foodItemId);
    return index >= 0 ? _items[index].quantity : 0;
  }

  // Checkout and create order
  Future<String?> checkout(String deliveryAddress) async {
    if (_items.isEmpty) {
      throw Exception('Cart is empty');
    }

    final userId = FirebaseAuth.instance.currentUser?.uid;
    if (userId == null) {
      throw Exception('User not authenticated');
    }

    // Convert cart items to order items
    final orderItems = _items.map((cartItem) {
      return OrderItem(
        foodItemId: cartItem.foodItem.id,
        name: cartItem.foodItem.name,
        quantity: cartItem.quantity,
        price: cartItem.foodItem.price,
        imageUrl: cartItem.foodItem.image, // Fixed: use 'image' property
      );
    }).toList();

    // Create order
    final order = Order(
      id: '', // Will be generated by Firebase
      userId: userId,
      items: orderItems,
      totalAmount: subtotal,
      status: 'pending',
      createdAt: DateTime.now(),
      deliveryAddress: deliveryAddress,
    );

    // Save to Firebase
    final orderId = await _orderService.createOrder(order);

    // 🔔 Trigger local notification on successful order
    if (orderId != null) {
      final notificationService = NotificationService();
      await notificationService.showOrderPlacedNotification(orderId);
      // Schedule a reminder for later
      notificationService.scheduleReminderNotification();
    }

    // Clear cart after successful checkout
    clearCart();

    return orderId;
  }
}

