// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9fAxxnDUgffX9RUaIs2XfTtDrhuzsi6Y',
    appId: '1:730987354561:web:01409fbc9de2d49e923740',
    messagingSenderId: '730987354561',
    projectId: 'foodapp-ce408',
    authDomain: 'foodapp-ce408.firebaseapp.com',
    storageBucket: 'foodapp-ce408.firebasestorage.app',
    measurementId: 'G-Z7V55FGTH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHhIgi-d0jTohMlp_GZV6cEcLMPfOhX78',
    appId: '1:730987354561:android:b9e65996ed1ae41f923740',
    messagingSenderId: '730987354561',
    projectId: 'foodapp-ce408',
    storageBucket: 'foodapp-ce408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArVpMPyy39xIjEtYyki0klxouLTE_2fGs',
    appId: '1:730987354561:ios:41f54a3cb79cd339923740',
    messagingSenderId: '730987354561',
    projectId: 'foodapp-ce408',
    storageBucket: 'foodapp-ce408.firebasestorage.app',
    iosBundleId: 'com.example.harvestboxRestaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArVpMPyy39xIjEtYyki0klxouLTE_2fGs',
    appId: '1:730987354561:ios:41f54a3cb79cd339923740',
    messagingSenderId: '730987354561',
    projectId: 'foodapp-ce408',
    storageBucket: 'foodapp-ce408.firebasestorage.app',
    iosBundleId: 'com.example.harvestboxRestaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9fAxxnDUgffX9RUaIs2XfTtDrhuzsi6Y',
    appId: '1:730987354561:web:51c88d9c60fea92b923740',
    messagingSenderId: '730987354561',
    projectId: 'foodapp-ce408',
    authDomain: 'foodapp-ce408.firebaseapp.com',
    storageBucket: 'foodapp-ce408.firebasestorage.app',
    measurementId: 'G-NMG1GNR3L4',
  );
}
